package me.itzisonn_.itzstandeditor.enums;

public enum CopyType {
    ROTATE_HEAD,
    ROTATE_LEFTARM,
    ROTATE_RIGHTARM,
    ROTATE_LEFTLEG,
    ROTATE_RIGHTLEG,

    APPEAR_PLATE,
    APPEAR_ARMS,
    APPEAR_INVISIBILITY,
    APPEAR_GLOWING,
    APPEAR_SMALL,
    APPEAR_GRAVITY,
    APPEAR_INVULNERABILITY,

    ARMOR_HEAD,
    ARMOR_CHEST,
    ARMOR_LEGS,
    ARMOR_FEET,
    ARMOR_HAND,
    ARMOR_OFFHAND
}