name: ItzStandEditor
version: '${project.version}'
main: me.itzisonn_.itzstandeditor.ItzStandEditor
api-version: '1.20'
author: ItzIsonn_
description: 'Редактирование Армор Стендов'

commands:
  itzstandeditor:
    description: Главная команда плагина

permissions:
  itzstandeditor.*:
    description: Все права
    children:
      itzstandeditor.reload: true
      itzstandeditor.open: true
  itzstandeditor.reload:
    description: Перезагрузка конфига
  itzstandeditor.open:
    description: Открытие меню редактирования